### ISSUE TITLE
Potential AirTrafficController/Landing/Timing Issue

### ISSUE THREAD

**Issue by rpont** [alexronquillo/optimal-airport#2]
Take a look at the times in the output of the model. Below is the first plane generated along with the times I added:
    "Plane 1 with HIGH priority and SMALL size arrives. Time: 0.0
    Air Traffic Controller signals Plane 1 to land.
    Plane 1 starts landing procedure. Time: 1.504
    Plane 1 landed. Time: 1.504"
Plane 1 would later takeoff at:
   "Plane 1 took off. Time: 4.506"
I am using the value of elapsedTime to print out times of events, either there is a better value to use or we've got some timing issues. Later in the simulation it also appears as though cleanup times vary from occuring instantly (no change in times from start to finish) to a couple seconds.

Thoughts?

**Comment by rpont** [comment]
Changed from elapsedTime to (System.currentTimeMillis()-Arrivals.getStartTime())/1000). Seemed to produce more consistent data. Opinions?

**Comment by alexronquillo** [comment]
I think it's because of the threads. I would try using a method which returns the time in the airport class.

**Comment by alexronquillo** [comment]
Fixed the bug and pushed the new, working project with consistent times.
