### ISSUE TITLE
First Potential GroundMovementController Assignment Issue

### ISSUE THREAD

**Issue by rpont** [alexronquillo/optimal-airport#3]
Assuming the elapsedTime is an appropriate way to tell timing in our system, I noticed these two anomolies in the output. Plane 13 and 15 although landing at different times get assigned the same Gate:
Plane 13 landed. Time: 22.545
Air Traffic Controller signals Plane 15 to land.
Plane 15 starts landing procedure. Time: 22.545
Plane 16 with LOW priority and MEDIUM size arrives. Time: 22.545
Plane 14 finishes receiving service at Gate 0. Time: 24.046
Plane 15 landed. Time: 24.046
Air Traffic Controller signals Plane 6 to takeoff.
Plane 6 starts takeoff procedure.  Time: 24.046
Plane 14 added to the departure queue.
Gate 0 starts cleaning procedure. Time: 24.046
Plane 8 took off. Time: 24.046
Air Traffic Controller signals Plane 14 to takeoff.
Plane 14 starts takeoff procedure.  Time: 24.046
Plane 10 added to the departure queue.
Gate 3 starts cleaning procedure. Time: 24.046
Plane 17 with MEDIUM priority and MEDIUM size arrives. Time: 24.046
Gate 0 finishes cleaning procedure. Time: 25.551
Gate 0 is available. Time: 25.551
Ground Movement Controller assigns Plane 13 to Gate 0.
Ground Movement Controller assigns Plane 15 to Gate 0.
Plane 13 starts receiving service at Gate 0. Time: 25.551
Plane 15 starts receiving service at Gate 0. Time: 25.551

**Comment by rpont** [comment]
Changed from elapsedTime to (System.currentTimeMillis()-Arrivals.getStartTime())/1000). Seemed to produce more consistent data. Opinions?

**Comment by alexronquillo** [comment]
Recreated the problem:

Ground Movement Controller assigns Plane 13 to Gate 0.
Ground Movement Controller assigns Plane 15 to Gate 0.
Plane 15 starts receiving service at Gate 0. Time: 0.019
Plane 13 starts receiving service at Gate 0. Time: 0.018

Fixed the problem by setting the availability of the gate in the ground controller class (once the gate is retrieved for the joint activity - which make more sense logically than waiting for the gate to start service to become unavailable.)

New Output:

Ground Movement Controller assigns Plane 13 to Gate 0.
Ground Movement Controller assigns Plane 15 to Gate 1.
Plane 15 starts receiving service at Gate 1. Time: 0.01
Plane 13 starts receiving service at Gate 0. Time: 0.01
Plane 15 finishes receiving service at Gate 1. Time: 3.019
Plane 13 finishes receiving service at Gate 0. Time: 3.019
Plane 15 added to the departure queue.
Gate 1 starts cleaning procedure. Time: 3.019
Gate 1 finishes cleaning procedure. Time: 4.024
Gate 1 is available. Time: 4.024
