### ISSUE TITLE
Second Potential GroundMovementController Assignment Issue

### ISSUE THREAD

**Issue by rpont** [alexronquillo/optimal-airport#4]
Same concept, this time Plane 17 and 18 land at the same time and get assigned the same Gate: 
Plane 17 landed. Time: 30.074
Air Traffic Controller signals Plane 10 to takeoff.
Plane 10 starts takeoff procedure.  Time: 30.074
Plane 11 added to the departure queue.
Gate 4 starts cleaning procedure. Time: 30.074
Plane 18 landed. Time: 30.074
Air Traffic Controller signals Plane 11 to takeoff.
Plane 11 starts takeoff procedure.  Time: 30.074
Plane 13 added to the departure queue.
Gate 0 starts cleaning procedure. Time: 30.074
Plane 21 with MEDIUM priority and LARGE size arrives. Time: 30.074
Gate 4 finishes cleaning procedure. Time: 31.576
Gate 4 is available. Time: 31.576
Ground Movement Controller assigns Plane 17 to Gate 4.
Ground Movement Controller assigns Plane 18 to Gate 4.
Plane 17 starts receiving service at Gate 4. Time: 31.576
Plane 18 starts receiving service at Gate 4. Time: 31.576
Gate 0 finishes cleaning procedure. Time: 31.576
Gate 0 is available. Time: 31.576
Plane 22 with LOW priority and SMALL size arrives. Time: 31.576
Plane 11 took off. Time: 33.077
Air Traffic Controller signals Plane 21 to land.
Plane 21 starts landing procedure. Time: 33.077
Plane 10 took off. Time: 33.077
Air Traffic Controller signals Plane 22 to land.
Plane 22 starts landing procedure. Time: 33.077
Plane 23 with MEDIUM priority and LARGE size arrives. Time: 33.077
Ground Movement Controller assigns Plane 22 to CargoBay 0.
Plane 22 landed. Time: 34.578
Air Traffic Controller signals Plane 20 to land.
Plane 20 starts landing procedure. Time: 34.578
Plane 22 starts receiving service at CargoBay 0. Time: 34.578
Plane 17 finishes receiving service at Gate 4. Time: 34.578
Plane 18 finishes receiving service at Gate 4. Time: 34.578

**Comment by rpont** [comment]
Changed from elapsedTime to (System.currentTimeMillis()-Arrivals.getStartTime())/1000). Seemed to produce more consistent data. Opinions?

**Comment by alexronquillo** [comment]
See the solution to the other bug.
