### ISSUE TITLE
The landing time for Plane 2 is very long

### ISSUE THREAD

**Issue by alexronquillo** [alexronquillo/optimal-airport#5]
Plane 2 starts landing procedure. Time: 0.021
Plane 1 landed. Time: 0.022
Ground Movement Controller assigns Plane 1 to CargoBay 0.
Plane 4 with LOW priority and MEDIUM size arrives. Time: 0.023
Plane 1 starts receiving service at CargoBay 0. Time: 0.024
Air Traffic Controller signals Plane 3 to land. Time: 0.027
Plane 3 starts landing procedure. Time: 0.027
Plane 3 landed. Time: 0.028
Ground Movement Controller assigns Plane 3 to Gate 0.
Plane 3 starts receiving service at Gate 0. Time: 0.028
Air Traffic Controller signals Plane 4 to land. Time: 0.03
Plane 4 starts landing procedure. Time: 0.031
Ground Movement Controller assigns Plane 4 to Gate 1.
Plane 4 landed. Time: 0.032
Plane 4 starts receiving service at Gate 1. Time: 0.032
Plane 5 with HIGH priority and SMALL size arrives. Time: 0.032
Air Traffic Controller signals Plane 5 to land. Time: 0.033
Plane 5 starts landing procedure. Time: 0.033
Ground Movement Controller assigns Plane 5 to Gate 2.
Plane 5 landed. Time: 0.033
Plane 5 starts receiving service at Gate 2. Time: 0.033
Plane 6 with LOW priority and SMALL size arrives. Time: 0.034
Plane 7 with MEDIUM priority and SMALL size arrives. Time: 0.036
Air Traffic Controller signals Plane 7 to land. Time: 0.037
Plane 7 starts landing procedure. Time: 0.038
Plane 8 with HIGH priority and LARGE size arrives. Time: 0.038
Plane 9 with LOW priority and SMALL size arrives. Time: 0.043
Plane 10 with LOW priority and LARGE size arrives. Time: 0.045
Plane 11 with LOW priority and MEDIUM size arrives. Time: 0.047
Plane 12 with HIGH priority and MEDIUM size arrives. Time: 0.049
Plane 13 with MEDIUM priority and MEDIUM size arrives. Time: 0.051
Plane 14 with HIGH priority and LARGE size arrives. Time: 0.053
Plane 15 with HIGH priority and LARGE size arrives. Time: 0.055
Plane 16 with HIGH priority and SMALL size arrives. Time: 0.057
Plane 17 with LOW priority and LARGE size arrives. Time: 0.059
Plane 18 with LOW priority and SMALL size arrives. Time: 0.061
Plane 19 with HIGH priority and SMALL size arrives. Time: 0.063
Plane 20 with MEDIUM priority and LARGE size arrives. Time: 0.065
Plane 21 with MEDIUM priority and LARGE size arrives. Time: 0.067
Plane 22 with LOW priority and MEDIUM size arrives. Time: 0.069
Plane 23 with HIGH priority and SMALL size arrives. Time: 0.071
Plane 24 with LOW priority and SMALL size arrives. Time: 0.092
Plane 25 with LOW priority and SMALL size arrives. Time: 0.094
Plane 26 with LOW priority and SMALL size arrives. Time: 0.096
Plane 27 with LOW priority and LARGE size arrives. Time: 0.098
Plane 28 with LOW priority and MEDIUM size arrives. Time: 0.1
Plane 29 with MEDIUM priority and SMALL size arrives. Time: 0.102
Plane 30 with LOW priority and SMALL size arrives. Time: 0.104
Plane 31 with LOW priority and LARGE size arrives. Time: 0.106
Plane 32 with MEDIUM priority and SMALL size arrives. Time: 0.108
Plane 33 with MEDIUM priority and MEDIUM size arrives. Time: 0.11
Plane 34 with LOW priority and MEDIUM size arrives. Time: 0.112
Plane 2 landed. Time: 0.114

**Comment by Padge91** [comment]
Interesting. Very interesting. If you look at plane 3 start landing / landed time, it is more normal. Same with plane 4. I'll look into it.
