### ISSUE TITLE
Sim Time

### ISSUE THREAD

**Issue by alexronquillo** [alexronquillo/optimal-airport#6]
The simulation period (simTime) is not an attribute of the arrivals, it is an attribute of the entire simulation, so I think it belongs in the simulation's main class: Airport. The arrival period is an attribute of the arrivals, so I think it is fine in the Arrivals class.

**Comment by Padge91** [comment]
Planes needs to know simTime to calculate landing/takeoff times. Made the sim time available from the airport class for the airplanes.
