### ISSUE TITLE
Rejected planes

### ISSUE THREAD

**Issue by alexronquillo** [alexronquillo/optimal-airport#7]
I think the user should be alerted when a plane is rejected, or else it looks as if the plane is in the arrivals queue, when in reality, it can't go into the full arrivals queue.

**Comment by Padge91** [comment]
The rejected planes calculation at the moment is only for planes that are in the Arrivals queue, but do not receive service before the end of the simulation. We need to decide how big the arrivals queue is allowed to be before planes are rejected because it is full.

**Comment by Padge91** [comment]
Rejected planes are now shown immediately and rejected immediately upon full Arrivals queue.
